apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: deploy-services
  labels:
    app: fastapi-service
spec:
  type: ClusterIP
  selector:
    app: fastapi-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
