{{- range $key, $svc := dict "fastifyService" .Values.fastifyService "nextjsService" .Values.nextjsService "fastapiService" .Values.fastapiService }}
{{- if and $svc.enabled $svc.hpa.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $svc.name }}-hpa
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $svc.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $svc.name }}
  minReplicas: {{ $svc.hpa.minReplicas }}
  maxReplicas: {{ $svc.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $svc.hpa.targetCPU }}
{{- end }}
{{- end }}
