{{- range $key, $svc := dict "fastifyService" .Values.fastifyService "nextjsService" .Values.nextjsService "fastapiService" .Values.fastapiService }}
{{- if $svc.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $svc.name }}-netpol
  namespace: {{ $.Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ $svc.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - podSelector:
            matchLabels:
              app: prometheus
      ports:
        - port: {{ $svc.port }}
          protocol: TCP
{{- end }}
{{- end }}
