apiVersion: v1
kind: ConfigMap
metadata:
  name: nextjs-service-config
  namespace: deploy-services
  labels:
    app: nextjs-service
data:
  PORT: "3002"
  NODE_ENV: "production"
  OTEL_SERVICE_NAME: "nextjs-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.deploy-services.svc.cluster.local:4318"
  NEXT_PUBLIC_BASE_URL: "http://localhost:3002"
