apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nextjs-service-netpol
  namespace: deploy-services
spec:
  podSelector:
    matchLabels:
      app: nextjs-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - podSelector:
            matchLabels:
              app: prometheus
      ports:
        - port: 3002
          protocol: TCP
